server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    add_header X-Service-Name "Frontend-Nginx";


    # SPA routing support: forward all non-file requests to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }

    error_page 404 /index.html;
}
