apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: mfulearnai
  labels:
    app: chat-service
    service: chat
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
  - name: http
    port: 5002
    targetPort: 5002
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
