global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'bedrock-gateway'
    static_configs:
      - targets: ['bedrock-gateway:8000']

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216'] 