apiVersion: v1
kind: Secret
metadata:
  name: department-service-secret
  namespace: default
type: Opaque
stringData:
  mongodb-uri: "mongodb://root:1234@mongodb-service:27017/mfu_chatbot?authSource=admin"
